version: '3.8'

services:
  web:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0

  db_mysql:
    image: mysql:latest
    container_name: mymysql
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
    restart: always